name: Kunals Blog
ighlighter: true
url: https://kunalkanojia.github.io
gems: [jekyll-paginate,  jekyll-gist]
paginate: 8
description: I can code
intro:
logo:             logo.png
disqus_shortname:

markdown:    kramdown

# Owner/author information
owner:
  name:          Kunal Kanojia
  avatar:
  email:          kanojia.kunal@yahoo.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:  _kkanojia
  github:   kunalkanojia
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80108133-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
